POST http://142.93.213.48:8000/api/post/delete_registration
content-type: application/json

{
    "name":"f",
    "id":"7msyn"
}
#########
POST http://192.168.0.106:8000/api/post/submission
content-type: application/json

{
    "name":"Raghunath Singh",
    "id": "ewi1a",
    "score": 90
}